[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]

runner = "./qemu-run.sh"

[source.crates-io]
replace-with = 'ustc' 

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index" 

[net]
git-fetch-with-cli = true